version: '3.9'

services:
  orderdelivery.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8085
    ports:
      - 8085:8085
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_secret_pass
      - POSTGRES_DB=OrderDelivery
    ports:
       - 5432:5432

  adminer:
    ports:
      - 8080:8080