version: '3.9'

networks:
  delivery-net:
     driver: bridge

services:
  orderdelivery.api:
    container_name: api
    image: borntowhine/order_delivery_api
    build:
      context: .
      dockerfile: OrderDelivery.API/Dockerfile
    networks:
      - delivery-net
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - delivery-data:/var/lib/postgresql/data
    networks:
      - delivery-net

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - delivery-net
    depends_on:
      - db

volumes:
  delivery-data:
  
