version: '3.9'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8085
      - DB_DATABASE=orderdelivery
      - DB_USERNAME=ps_user
      - DB_PASSWORD=ps_pass
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 8085:8085
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  app:
    ports:
      - 3000:3000

  proxy:
    ports:
       - 5142:8085

  db:
    environment:
      - POSTGRES_USER=ps_user
      - POSTGRES_PASSWORD=ps_pass
      - POSTGRES_DB=orderdelivery
    ports:
       - 5432:5432

  adminer:
    ports:
      - 8080:8080