version: '3.9'

networks:
  delivery-net:
     driver: bridge

services:
  api:
    container_name: api
    image: borntowhine/order_delivery_api
    build:
      context: .
      dockerfile: OrderDelivery.API/Dockerfile
    networks:
      - delivery-net
    depends_on:
      - db
   
  app:
    container_name: app
    image: borntowhine/order_delivery_app
    build:
      context: order-delivery-frontend/
      dockerfile: Dockerfile
    networks:
      - delivery-net
    depends_on:
      - proxy

  proxy:
    container_name: proxy
    image: borntowhine/order_delivery_proxy
    build:
      context: order_delivery.proxy/
      dockerfile: Dockerfile
    networks:
      - delivery-net
    depends_on:
      - api

  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - ./delivery-data:/var/lib/postgresql/data
    networks:
      - delivery-net

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - delivery-net
    depends_on:
      - db

volumes:
  delivery-data:
  
